mongo = new Mongo("localhost");
newDB = mongo.getDB("newDB");
collections = newDB.getCollectionNames();
print("Initial Collections:");
printjson(collections);
newDB.createCollection("newCollectionA");
newDB.createCollection("newCollectionB");
print("After Collection Creation:");
collections = newDB.getCollectionNames();
printjson(collections);